import type { Metadata } from "next";
import "../globals.css";
import { I18nProvider, type Locale } from "@/i18n/I18n-provider";

export default async function LocaleLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale: maybeLocale } = await params;
  const locale = (maybeLocale ?? "en") as Locale;
  return <I18nProvider initialLocale={locale}>{children}</I18nProvider>;
}

export async function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fr" }];
}

export async function generateMetadata({
  params,
}: LayoutProps<"/[locale]">): Promise<Metadata> {
  const { locale: maybeLocale } = await params;
  const l = (maybeLocale ?? "en") as Locale;
  return {
    alternates: {
      languages: {
        en: "/en",
        fr: "/fr",
      },
    },
    // Optionally adapt titles/descriptions here per-locale
    title: l === "fr" ? "Application Next" : "Create Next App",
    description:
      l === "fr"
        ? "Généré par create next app"
        : "Generated by create next app",
  };
}
